agent:
  label: jenkins-jx-base
  container: jx-base
pipelines:
  pullRequest:
    build:
      steps:
        - sh: make build
          name: build
        - dir: charts/REPLACE_ME_APP_NAME
          steps:
              - sh: jx step helm build
                name: helm-build

  release:
    build:
      steps:
        - sh: make release
          name: release
  promote: