agent:
  label: docker.io/golang:1.12.1
  container: go
pipelines:
  pullRequest:
    build:
      steps:
        - sh: make build
          name: build
        - dir: charts/REPLACE_ME_APP_NAME
          steps:
          - sh: jx step helm build
            name: helm-build

  release:
    build:
      steps:
        - sh: make build
          name: build
        - dir: charts/REPLACE_ME_APP_NAME
          steps:
          - sh: make tag
            name: tag
          - sh: jx step helm build
            name: helm-build
          - comment: Version the helm chart
            sh: jx step helm version
            name: helm-version
    promote:
      build:
        steps:
          - sh: make release
            name: release
          - dir: charts/REPLACE_ME_APP_NAME
            steps:
            - comment: Let's release the helm chart
              sh: jx step helm release
              name: helm-release
            - comment: Let's promote through all 'Auto' promotion Environments
              sh: jx promote -b --all-auto --timeout 1h --version \$(cat ../../VERSION)
              name: jx-promote